import { Metadata } from "next";
import "./globals.css"

export const metadata: Metadata = {
  title: "타임투게더",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <title>Time Together</title>
      </head>
      <body className="bg-gray-100 text-gray-800">
        {children}
      </body>
    </html>
  );
}